# .github/workflows/publish.yml
name: Publish to pub.dev

on:
  push:
    tags:
    - 'v[0-9]+.[0-9]+.[0-9]+' # tag pattern on pub.dev: 'v{{version}'


jobs:
    publish:
      uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
      permissions:
        id-token: write # Required for authentication using OIDC
        pull-requests: write # Required for writing the pull request note